Repository cse110-sp24-group4/cse110-sp24-group4, pull requests merged in 2024-05, with the labels that each got.

#13 Project page
  README.md
  docs/js/global.html
  docs/js/index.html
  docs/js/js_project.js.html
  docs/js/js_testing-prettier.js.html
  docs/js/test.js.html
  package-lock.json
  source/css/project.css
  source/js/project.js
  source/pages/project.html
  specs/pseudo/landingpage.md
  specs/pseudo/projectpage.md
Labels: documentation, enhancement

#54 added force push to jsdoc workflow closes #53
  .github/workflows/jsdoc.yml
Labels: bug

#55 udpated github_tokens to refer to automation-bot
  .github/workflows/jsdoc.yml
Labels: bug

#61 combined prettier and jsdoc into a single commit and push closes #53
  .github/workflows/jsdoc.yml
  package.json
Labels: documentation

#82 media query for landing page
  source/css/index.css
  specs/design_pages/notes.drawio.png
Labels: enhancement, main-page-js

#88 Sort notes button that sorts by date created closes #48
  eslint.config.mjs
  source/js/__testing__/puppeteer/notes.test.js
  source/js/notes.js
  source/pages/notes.html
Labels: note page

#110 Pwa and service worker
  source/css/index.css
  source/css/main.css
  source/css/notes.css
  source/js/__testing__/puppeteer/notes.test.js
  source/js/notes.js
  source/js/project.js
  source/manifest.json
  source/pages/notes.html
  source/pages/project.html
  source/sw.js
Labels: enhancement
